#!/bin/python3

import math
import os
import random
import re
import sys
import collections
# Complete the anagram function below.
def anagram(s):
    l = len(s)
    count=0
    if l%2!=0:
        return -1
    s1=s[:l//2]
    s2=s[l//2:]
    counts  = collections.Counter(s1)
    counts.subtract(s2)
    print(counts)
    for i in counts.values():
        if i<0:
            count+=abs(i)
    return count
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        s = input()

        result = anagram(s)

        fptr.write(str(result) + '\n')

    fptr.close()
