#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the isBalanced function below.
def isBalanced(s):
    leftBraces='{[('
    rightBraces='}])'
    comp = {a:b for a,b in zip(leftBraces,rightBraces) }
    stack=[]
    for i in s:
        if i in leftBraces:
            stack.append(i)
        elif i in rightBraces:
            #check if stack is empty, if not pop the value
            if not stack or comp[stack.pop()]!=i:
                return 'NO'
    if len(stack)==0:
        return "YES"
    return "NO"
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        s = input()

        result = isBalanced(s)

        fptr.write(result + '\n')

    fptr.close()
