#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter
# Complete the beautifulPairs function below.
def beautifulPairs(A, B):
    i = 0 
    j=0 
    print(Counter(A) , Counter(B))
    ca , cb = Counter(A) , Counter(B)
    common=0
    for k in ca.keys():
        print(ca[k] , cb[k])
        common+=min(ca[k] ,cb[k])
    if common==n:
        return common-1
    else:
        return common+1

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    A = list(map(int, input().rstrip().split()))

    B = list(map(int, input().rstrip().split()))

    result = beautifulPairs(A, B)

    fptr.write(str(result) + '\n')

    fptr.close()
