#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the flatlandSpaceStations function below.
def flatlandSpaceStations(n,c):
    c.sort()
    distances=[]
    distances.append(c[0])
    distances.append((n-1)-c[-1])
    print(distances)
    for i in range(len(c)-1):
        mean=math.floor((c[i+1]-c[i])//2)
        print("means -->"  , mean)
        distances.append(mean)
    print(distances)
    return max(distances)
    
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    c = list(map(int, input().rstrip().split()))

    result = flatlandSpaceStations(n, c)

    fptr.write(str(result) + '\n')

    fptr.close()
