#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the funnyString function below.
def ordinal(s):
    result=[]
    for i in s:
        result.append(ord(i))
    return result
def funnyString(s):
    revS=s[::-1]
    print(s)
    x=ordinal(s)
    y=ordinal(revS)
    diff=[]
    diff1=[]
    for i in range(len(x)-1):
        diff.append(abs(x[i]-x[i+1]))
        diff1.append(abs(y[i]-y[i+1]))
    if diff==diff1:
        return "Funny"
    return "Not Funny"
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        s = input()

        result = funnyString(s)

        fptr.write(result + '\n')

    fptr.close()
