#!/bin/python3

import math
import os
import random
import re
import sys
import itertools
# Complete the maximumPerimeterTriangle function below.
def maximumPerimeterTriangle(sticks):
    sides=[]
    sticks = list(itertools.combinations(sticks,3))
    for i in sticks:
        if i[0]+i[1]>i[2] and i[1] + i[2]>i[0] and i[2]+i[0]>i[1]:
            sides.append([i[0],i[1],i[2]])
    maxVal=0
    res=0
    for i in sides:
        if sum(i)>maxVal:
            maxVal=sum(i)
            res=i
    # print(sides)
    if res!=0:
        res.sort()
        print(*res)
    else:
        print( -1)

n = int(input())

sticks = list(map(int, input().rstrip().split()))

(maximumPerimeterTriangle(sticks))

