#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the minimumSwaps function below.
def minimumSwaps(arr):
    swaps=0
    i=0
    while i<len(arr)-1:
        if arr[i]!=(i+1):
            arr[arr[i]-1],arr[i]=arr[i] ,arr[arr[i]-1]          
            swaps+=1
        else:
            i=i+1
    return swaps
n = int(input())
arr = list(map(int, input().rstrip().split()))
     
res = minimumSwaps(arr)
print(res)

