#!/bin/python3

import math
import os
import random
import re
import sys


# Complete the pangrams function below.
def pangrams(s):
    count=0
    s=s.lower().replace( " " , "")
    cntr = set(s)
    for i in cntr:
        count+=1
    if count==26:
        return "pangram"
    return "not pangram"
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = pangrams(s)

    fptr.write(result + '\n')

    fptr.close()
